

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  namespaceSelector:
    matchExpressions:
    - key: runlevel
      operator: NotIn
      values: ["dxp"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: NoneOnDryRun
  rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCekNDQXUrZ0F3SUJBZ0lVQ3RhUEdBMDhzdzlvNkovUjdHYitPc3lOY0dJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NqRUxNQWtHQTFVRUJoTUNRMDR4RWpBUUJnTlZCQWdUQ1VkMVlXNW5XbWh2ZFRFU01CQUdBMVVFQnhNSgpSM1ZoYm1kYWFHOTFNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFY01Cb0dBMVVFCkF4TVRhM1ZpWlhKdVpYUmxjeTFUYjNWc2JXRjBaVEFlRncweU1EQXhNREl3TVRNM01EQmFGdzB5TVRBeE1ERXcKTVRNM01EQmFNR014Q3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSUV3bEhkV0Z1WjFwb2IzVXhFakFRQmdOVgpCQWNUQ1VkMVlXNW5XbWh2ZFRFTU1Bb0dBMVVFQ2hNRGF6aHpNUTh3RFFZRFZRUUxFd1pUZVhOMFpXMHhEVEFMCkJnTlZCQU1UQkc1MWQyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDK1BwWFgKQXhVbDNwd0taZlZHdHVOMktueVR5QkVPWElsRk9RdDBYSk5PdkpFNUlaMmxRZUo3K0VrS2ZQRldJYmNuQVdjTgp2WHlkNDlkZndJZWY3SWNQc3I1a01DZjdsR2owN0E1bTNicldhVm9FREthYldFdWNrWVRZVFFydU53OFljMW0rCm5YZFUvc3Q4NTRXQktmSDlkS2dDaVNGcGYvVEdkVmZqb2xOV2dQQVdZVnI2UXE1d3dLRHc4a255cnB0V2RnUmMKcWJ5dXdJK0JoM1VhL21TTmNZUHdNRmxVY1plTWkzS0loQzZJZ1lIeVYvVXdGOVFpRlFEblFQRlFQam1xQW5ydgp0RkFmekxUSEgvbnVvZmxzTkt2WG52RUZKczBnZzhRODg4NWYrbWM2YWFtek1Wc2xScEJoZE9PMmp0UFdPSDErCm4yTnFnUmZmUkxOeDk2RWxBZ01CQUFHamdhTXdnYUF3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVcKTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRcwo4Mi9uY09kL2pRK0YyVjRMbmtVa0RXUzJZREFmQmdOVkhTTUVHREFXZ0JTS2ZndkpyVkdRaXhKZWUzdjVwR09RCk5CYkFZVEFoQmdOVkhSRUVHakFZaHdRS0FZektod1FLQVl4VGh3UUtBYlIraHdUQXFBTkVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCa1lZR3hOd2JlZi8wclFJVGNmZnBWa05lR0o5eFVidldkMC8rU3hoNWswNWMzaFB3agplRU8vTm5IS3B3OUtEcGIrV3dKNFU1TStFYTFIRnhKZ2srbXhSaVo4K1dsZ1R2NlEya0grTTUxY2F3bHVEYzd2Ck1lOHB3Y3ZUeGI1VkJZNFIxTkVCakljSEl3cXUvUzhzODhaRmFJKzFyNnU1ZnhVTERTbTRIZUVXTXJBSnhuam0KeHJaOFJOZ2ErZE1kRFVYSWRiLzl6T043VHQwaUFJYWdWYmN0ZXBFVndpR3RoN2RDblpNLy80NjFDV2szZWdNYQorOFJGTnJPQngxcXZlQ1hZbjZNbTZoV0Jqa0ZVWWFZeGhJSGtkRU5XaHMxbVJxUm4zbFVDaGRYZnZiT2NUVFdOCklaQVJtUG54N05PUkJKdk5oWjhISHZtTzdtZ1VRdkpFUHJiQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://10.1.180.126:443/mutating-pods
