---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  namespaceSelector:
    matchExpressions:
    - key: runlevel
      operator: In
      values: ["dxp"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: NoneOnDryRun
  rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBVENDQXVtZ0F3SUJBZ0lVU1lwZklOS09hUk56bkIrenNoblVBclE0UWxVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NqRUxNQWtHQTFVRUJoTUNRMDR4RWpBUUJnTlZCQWdUQ1VkMVlXNW5XbWh2ZFRFU01CQUdBMVVFQnhNSgpSM1ZoYm1kYWFHOTFNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFY01Cb0dBMVVFCkF4TVRhM1ZpWlhKdVpYUmxjeTFUYjNWc2JXRjBaVEFlRncweE9URXlNVEF3T0RFMk1EQmFGdzB5TURFeU1Ea3cKT0RFMk1EQmFNR014Q3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSUV3bEhkV0Z1WjFwb2IzVXhFakFRQmdOVgpCQWNUQ1VkMVlXNW5XbWh2ZFRFTU1Bb0dBMVVFQ2hNRGF6aHpNUTh3RFFZRFZRUUxFd1pUZVhOMFpXMHhEVEFMCkJnTlZCQU1UQkc1MWQyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDWXF5TlgKbDcwS053bDdTcEs2SVExbWRmdFlQK2tPVURLcDYzQU9EaDJUckJKdWQvSHVQVkY0SXhyK29EdFh1N2ZzZDQyRAppUHo1emMxdDg3YjJKVUpGNERyckhuMVZRbTVoTXcwdnFVUVBpRm9pSStXYUdoc0ZpN2VWbmJEbnRXSmpROStmCm90N0o3YU9qeC9QMVBzaXNWVnBhaWlZbnBVZHQ5Wk9BakJld3c1MWl0U213ampSdDV5QzVRSzVOaGM3YXcvRGsKYUhIWnd1QmJWbVYvWlBGcjFsSmh3d0duZmtNRjM4TlRUd2Zlc2VkeW5jemF1blc0VlhScTFRcGZlVzlhRStHUApNQVZqRU9QYnpTNGZYbm9tYUVybE9pZ1p5MkNMdXVBK2h2Y1dBODNXbDFsKy92MUNWQWNLa0lSeFZEZjU0NHhwCnRuWitCenNJa0RkdHE1NHBBZ01CQUFHamdaMHdnWm93RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVcKTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUMQpNcU9DVldYTlIxZUMxVGhLN0NkQ2Q0ekUzekFmQmdOVkhTTUVHREFXZ0JUN0RWK1IxbEZLUkdaaW9GN1V2VG9NCnRRNWpIREFiQmdOVkhSRUVGREFTaHdRS0FZektod1FLQVl4VGh3UUtBYlIrTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQmVjaHFHS1FlSlNsVmQ1M0ViYkcwMllVT0Y2Z0RyY0I0MW5CdlJidEl2K3hsMmpXRTdQMnE2UFZPUgpwQUdjQTk3cUJzR2o2eUY0VytUSm53S3BHc1JRTGRoSUJkZGFLb05rZ1lCYnl0SHJucnRGeGNPV3kwdXFxRGtDCnExb3V1eUY0aGNFM1B4VWJSTjQrbmVFZmdXbW9sNHladVpkZUR6bEhyN1RZMlBndzIzdDFoUmpmdklHK1NOU2IKWTlWcURBTmR3VTNObWF3YmU1cjVGWkgrWStSbG1URWhhK1JQT0k4QW5rWldnQ3FQOUxRVEJIOXpIRnR1UzQ0OQo4eFRzOHJNNndvTU9HSkNob1dHY3VHc2FKWHJRclFwaC9Gc25UbitaSHdOeis2R2htZFRQcUdyVXlkeXU1Y1JJCjJkQkxsWE5WRENwdUlMNFpRTGR3YXd1UmhTS28KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://10.1.140.202:443/mutating-pods
