apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuwa-controller
  namespace: system
  labels:
    control-plane: nuwa-controller
spec:
  selector:
    matchLabels:
      control-plane: nuwa-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: nuwa-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        volumeMounts:
          - name: ssl
            mountPath: "/ssl"
            readOnly: true
        resources:
          limits:
            cpu: 2048m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: ssl
          secret:
            secretName: kube-nuwa-secret
      terminationGracePeriodSeconds: 10
