apiVersion: v1
kind: Service
metadata:
  metadata:
  labels:
    control-plane: controller-manager
  name: nuwa-sidecar-injector
  namespace: system
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    control-plane: controller-manager
    app: nuwa-sidecar-injector