apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: webhook-service
  namespace: system
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  ports:
  - port: 1443
    targetPort: 1443

