apiVersion: nuwa.nip.io/v1
kind: StatefulSet
metadata:
  name: sample
spec:
  replicas: 3
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      readinessGates:
        - conditionType: InPlaceUpdateReady
      containers:
        - name: main
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 2
      partition: 2
