apiVersion: nuwa.nip.io/v1
kind: StatefulSet
metadata:
  name: sample
spec:
  replicas: 5
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      annotations:
        coordinates: '[{"room":"A","cabinet":"W-01","host":"node2","replicas":1},{"room":"A","cabinet":"S-02","host":"node3","replicas":2},{"room":"B","cabinet":"W-01","host":"node4","replicas":1},{"room":"B","cabinet":"S-02","host":"node5","replicas":1}]'
      labels:
        app: sample
    spec:
      readinessGates:
        - conditionType: InPlaceUpdateReady
      containers:
        - name: main
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 2
      partition: 2
