
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlRENDQW1DZ0F3SUJBZ0lVTTNDNkZBZVZIbkZVTXBxdEwwdDBnaXRUT3BRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4SERBYUJnTlZCQU1URTJ0MQpZbVZ5Ym1WMFpYTXRVMjkxYkcxaGRHVXdIaGNOTWpBd016SXhNVFl4TnpBd1doY05NakV3TXpJeE1UWXhOekF3CldqQXVNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFTk1Bc0dBMVVFQXhNRWJuVjMKWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmVYSzM0UUVPYzd0bWE4cjNSaAp1amIwM1RpSjVHMS8vd3JNdUJveUQxYklWUDlXZG1zTjZoTWlKMWgxeWtSUmFabmlQcmZramMza3dWU1E2REpSCkZuSW1NbFB0cmhJcW9ZMmFoUGwxRkFzekQ1VFVvTmJMTGZuWDhiVFhmQWdQM1BDRGJDd3lmK0FWZ1VxOXBrQmMKbjY2UGVGKzRLS3JqRWxkRjNHTHZmWDVySnBNSXhRQVRTMzJxbkdlSmlZNTUxdDZ6Zkhza01MNGNFN2hNOUYxNQpYZkQxMXgwbDBUUUFzSkd3RnZlL05UYkMyRFhtbmxJZCtNeG9xNnFnQ3pnejZhSkh6RU9aOU9SYkpZYWlOWDU3CmZTTUJlTC8wWDhDSzNaT2VCMU00bXFyYlVqSXZsb1VxcyswbUN1M3VZY1FSSmQyRlRTN1Mra3grbzAvZkxPVk4KZ04wQ0F3RUFBYU4vTUgwd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQgpCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU2hiNzA3dUhRYXRaWHJMMFJtCmFqVG1nblZuSGpBZkJnTlZIU01FR0RBV2dCU3dPWElETndDM3RvTU9PZzlibFBjeEVOZGM3VEFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVFFQWg0Vm9hVzNkS09Rdmd1YnZBYjRUSTRPU0tDZHcxcldGSG9UUmlLR0taY2thTy9tNQpyTFprVURmK1laUy9FMnJ1bVVueGtFN3ErS1pzaDZwQ2hjb0FIckF3R2pUVDVId3h1dEZRZWdrZkdXU2dTSFZKCnloaHE1RUlMK0o2bnhqSGM5dWlxTURaTkorK1dhaEMwV3N6UnYyb2lXNkhEeVpDeXZTaEZUdW5ZdFZ4ejhFcGIKZ0dvWHFFTk1JSFVlYjNGVUF6SGFFYytLWllNK0pKNWNzR3h4RWNzRU1nbDhmc0twSUpicEJFaEtmNUsxSlhqZApwdGtWbEdoVitpbkdmeGlQaEN6elFFVXFkdzZ2UEppOGdwbmtVNmN0R1JXWkZLdEVKSjFzbGZJa0tFNFdhODhPCitMcURHYzJ3VGI3NlMrcGhsdXhXSlBUb1drZ0MxKzdmdnNURlBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nuwa-nip-io-v1-stone
  failurePolicy: Fail
  name: mstone.kb.io
  rules:
  - apiGroups:
    - nuwa.nip.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stones

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlRENDQW1DZ0F3SUJBZ0lVTTNDNkZBZVZIbkZVTXBxdEwwdDBnaXRUT3BRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4SERBYUJnTlZCQU1URTJ0MQpZbVZ5Ym1WMFpYTXRVMjkxYkcxaGRHVXdIaGNOTWpBd016SXhNVFl4TnpBd1doY05NakV3TXpJeE1UWXhOekF3CldqQXVNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFTk1Bc0dBMVVFQXhNRWJuVjMKWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmVYSzM0UUVPYzd0bWE4cjNSaAp1amIwM1RpSjVHMS8vd3JNdUJveUQxYklWUDlXZG1zTjZoTWlKMWgxeWtSUmFabmlQcmZramMza3dWU1E2REpSCkZuSW1NbFB0cmhJcW9ZMmFoUGwxRkFzekQ1VFVvTmJMTGZuWDhiVFhmQWdQM1BDRGJDd3lmK0FWZ1VxOXBrQmMKbjY2UGVGKzRLS3JqRWxkRjNHTHZmWDVySnBNSXhRQVRTMzJxbkdlSmlZNTUxdDZ6Zkhza01MNGNFN2hNOUYxNQpYZkQxMXgwbDBUUUFzSkd3RnZlL05UYkMyRFhtbmxJZCtNeG9xNnFnQ3pnejZhSkh6RU9aOU9SYkpZYWlOWDU3CmZTTUJlTC8wWDhDSzNaT2VCMU00bXFyYlVqSXZsb1VxcyswbUN1M3VZY1FSSmQyRlRTN1Mra3grbzAvZkxPVk4KZ04wQ0F3RUFBYU4vTUgwd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQgpCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU2hiNzA3dUhRYXRaWHJMMFJtCmFqVG1nblZuSGpBZkJnTlZIU01FR0RBV2dCU3dPWElETndDM3RvTU9PZzlibFBjeEVOZGM3VEFOQmdrcWhraUcKOXcwQkFRc0ZBQU9DQVFFQWg0Vm9hVzNkS09Rdmd1YnZBYjRUSTRPU0tDZHcxcldGSG9UUmlLR0taY2thTy9tNQpyTFprVURmK1laUy9FMnJ1bVVueGtFN3ErS1pzaDZwQ2hjb0FIckF3R2pUVDVId3h1dEZRZWdrZkdXU2dTSFZKCnloaHE1RUlMK0o2bnhqSGM5dWlxTURaTkorK1dhaEMwV3N6UnYyb2lXNkhEeVpDeXZTaEZUdW5ZdFZ4ejhFcGIKZ0dvWHFFTk1JSFVlYjNGVUF6SGFFYytLWllNK0pKNWNzR3h4RWNzRU1nbDhmc0twSUpicEJFaEtmNUsxSlhqZApwdGtWbEdoVitpbkdmeGlQaEN6elFFVXFkdzZ2UEppOGdwbmtVNmN0R1JXWkZLdEVKSjFzbGZJa0tFNFdhODhPCitMcURHYzJ3VGI3NlMrcGhsdXhXSlBUb1drZ0MxKzdmdnNURlBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-nuwa-nip-io-v1-stone
  failurePolicy: Fail
  name: vstone.kb.io
  rules:
  - apiGroups:
    - nuwa.nip.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stones
