apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook-configuration"
webhooks:
  - name: "mutating-webhook-configuration"
    namespaceSelector:
      matchExpressions:
        - key: nuwa-injection
          operator: In
          values: ["enabled"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: NoneOnDryRun
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVoekNDQTIrZ0F3SUJBZ0lVTkpGN0kzY09keG5EbGV2OVlFSUtRdEhEdVdZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4SERBYUJnTlZCQU1URTJ0MQpZbVZ5Ym1WMFpYTXRVMjkxYkcxaGRHVXdIaGNOTWpBd016STBNVEF6TkRBd1doY05NakV3TXpJME1UQXpOREF3CldqQmpNUXN3Q1FZRFZRUUdFd0pEVGpFU01CQUdBMVVFQ0JNSlIzVmhibWRhYUc5MU1SSXdFQVlEVlFRSEV3bEgKZFdGdVoxcG9iM1V4RERBS0JnTlZCQW9UQTJzNGN6RVBNQTBHQTFVRUN4TUdVM2x6ZEdWdE1RMHdDd1lEVlFRRApFd1J1ZFhkaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMXRIeHZ2Z2s5MmdECmQyRTU0eklpcEZyTHQvcyt2RDBxUkZRYk5kUi9GZHp4QXFqVVY5VExaamVWdURrZUNWOEVuZzI4ZHphNGx3TGMKZ09HQmZCRTF2TmRVQnNOTThRYWQ3Q1VFMVNOR0hHMlJHU1JzZ1dDN1kzem5VRU84TVZmZ1pCbER0anV2QUFENwo1dnF5QXZFSytTOW1CcXhMYUxBVmtQMmNHUFZxNGgvbTJtRFpISEZxSEtoR1RaQXFCNjJPVzdPbGQ5ZmY0YVNnCmZjejBFWDg0eXorTEIwVm9nYWFzUU8xRFFkZDQrZjVWcTNpUnNyWkZkcWJlMWVzV2tMdFZjK2J4S2ZLUHcwSDcKMitUemdtL1hFR01yOThxOThQTGdDcy9QMXphMHRlTDhDalMwU3dBYWNvWXpJb21RUTdBMlN4K1FRZnpLSXNodQpUQmY3emxRVTd3SURBUUFCbzRJQlZ6Q0NBVk13RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHCkNDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTa1VrL0cKZDNWMW5JTDJLVktqL002WEtJaER5akFmQmdOVkhTTUVHREFXZ0JUcnRja092c3p3MWN4ZTJTKy92RVpwTGNJVwp1ekNCMHdZRFZSMFJCSUhMTUlISWdpOXVkWGRoTFdOdmJuUnliMnhzWlhJdGJXRnVZV2RsY2kxelpYSjJhV05sCkxtNTFkMkV0YzNsemRHVnRMbk4yWTRJeGJuVjNZUzFqYjI1MGNtOXNiR1Z5TFcxaGJtRm5aWEl0YzJWeWRtbGoKWlM1emRtTXVZMngxYzNSbGNpNXNiMk5oYklJbmJuVjNZUzF6YVdSbFkyRnlMV2x1YW1WamRHOXlMbk4yWXk1agpiSFZ6ZEdWeUxteHZZMkZzZ2psdWRYZGhMV052Ym5SeWIyeHNaWEl0YldGdVlXZGxjaTF0WlhSeWFXTnpMWE5sCmNuWnBZMlV1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVuVStpVGMKa0tBUHZSUTh5N2RVRmR5UXdiQlNjUU10TkRIc3ZIdW03b1dBOWhDQjZHNjFKdEFLYm5QWHFMRVRsVFRWYzRZaQozTHZOSzRESW0rQjFiQWlBOWRiaHlqbWVhZWlTSThDVTErN08zUmE4eUF4OXd4WFJlR1NYcWNYQXZZZStUQnFTCmRRQ1grZzVXT2o2NkYrNnFUT0RHdFdkOWpmTDBtUThyclpxckpnL1NsbXlLcUt1eTFTK2t5bUlLWEhtcFBxRWIKNDAvdUZGT2R4NUs5Y2x3aTNib0kwMGw3Wm9lNzVxNUpGMTZ6aXh1c0d2V3FnaGsrTGNQbzJkMjR0L3dUbXZ0RQpVR0UwWnpqMFlvbldwdWZOeVY3RlpabWtRcVlBVG90a202T014eDBLcWZ6cEpmUU8xNjRjNnR4TEV5S2xBV2RuCkZoS3FyT3ZOUUp4VXEzWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name:  nuwa-controller-manager-service
        namespace: nuwa-system
        path: /mutating-pods
    failurePolicy: Fail
    name: injector.nuwa.io
