apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook-configuration"
webhooks:
- name: "mutating-webhook-configuration"
  objectSelector:
    matchLabels:
      foo: bar
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: NoneOnDryRun
  rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVLRENDQXhDZ0F3SUJBZ0lVYzN0ajMvWUs0NmtsT1Q4RWFEK2ZqRW1SR29Fd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2NqRUxNQWtHQTFVRUJoTUNRMDR4RWpBUUJnTlZCQWdUQ1VkMVlXNW5XbWh2ZFRFU01CQUdBMVVFQnhNSgpSM1ZoYm1kYWFHOTFNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFY01Cb0dBMVVFCkF4TVRhM1ZpWlhKdVpYUmxjeTFUYjNWc2JXRjBaVEFlRncweU1EQXpNakV4TnpFNU1EQmFGdzB5TVRBek1qRXgKTnpFNU1EQmFNR014Q3pBSkJnTlZCQVlUQWtOT01SSXdFQVlEVlFRSUV3bEhkV0Z1WjFwb2IzVXhFakFRQmdOVgpCQWNUQ1VkMVlXNW5XbWh2ZFRFTU1Bb0dBMVVFQ2hNRGF6aHpNUTh3RFFZRFZRUUxFd1pUZVhOMFpXMHhEVEFMCkJnTlZCQU1UQkc1MWQyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDamYwSk4KN01VZnloVVpTRWFwdER5MjdoMFg3OFFiWXUyaWI1MEtCWFU1TlBEdTZnRUc3Vks5dGlGSEtlK0FrT1AvVUNSRwpxNVFHR3lPWTVHbWRhNmJvWFlMMWpzNDF5bVNYZm1wTXEyUTljUi9JM1EvdXNlK3A4RXVZVmU2VWR5RzFqcUYrCm8rWVhjKytoZ3JXUkl5eW81L0tZS3VidkdmR3RCUGZDUGFXODg1NUd6T1pxUDJ6dkg4a0c1RlAyUW1iMGduK2cKeEZJRXNUOFhITUp4eFRGZXBGMmxoZUpFREtnbkZIeUhYNENQVUp5VytsZ3VsK2VXVjdlL1hmMTkrZk5tT0FWawpRa0FVQ21XUE9YU2ZnWWdKY1A5VGVGcjd0cFBlZnRoSDVIN1ZoZ0Q2RGhranI4MDhwWmN4NStCdk1ZMlpEd3I2ClhodW5ybUlWS3B2OVlXRVZBZ01CQUFHamdjUXdnY0V3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVcKTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTLwpBcjNZT2lVMmhYc0t4bTFuMDl6ZzhOL05qREFmQmdOVkhTTUVHREFXZ0JTMXhETk1IN0xQV0huUDRybVlSWll1CnhXZmFwREJDQmdOVkhSRUVPekE1Z2pGdWRYZGhMV052Ym5SeWIyeHNaWEl0YldGdVlXZGxjaTF6WlhKMmFXTmwKTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzaHdSL0FBQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNHU2ZUeQpmR1J2NkJtVmxoamcwdU53ekx4R3JFcFZwK2tjUTk5VnNSam42QUtzOEZlc01nZklJK3V4WmZlN1ZGQjhKSXFVCk9qQUtVZlk0RHRza2lXVytJc2lLWCs0aW96bDgrdENQY24rQXRCa0NFUjFNbmhMN3JOa3UyNzYrV0Z4dE4raTYKRmptcmZ3Z2lMNmZSWWVxKzlUZGh0bnl4eHgzVFVKaFhKdWhxRXB6MWxpNTVWNVJ0dkRQWmNVY2I1OGtSdVhoOQpOUzNtZ21mQjJWWGdVZjB3WXhMTFNxcUxzZkNLZ0cybHNSTUlreE1UTUYxdFFIN1RqS3lkbGhNc0gyZTNPVkdXCnBKRmNFakMyRTZWOUhyT2hpYnFnNzVSbnRRRnBkRkNhUEFNVlZqSkxXYmhpSmhaazhqM1l6LzNoYnQwYU13ajkKNVdsRE54NmJNaG1rNnF5UAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name:  controller-manager-service
      namespace: system
      path: /mutating-pods
  failurePolicy: Fail
  name: injector.nuwa.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods