apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook-configuration"
webhooks:
- name: "mutating-webhook-configuration"
  objectSelector:
    matchLabels:
      foo: bar
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: NoneOnDryRun
  rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXhTZ0F3SUJBZ0lVUTA4QXA5YWVzUTlnbHgvem9MZ2JwQXFHT3Awd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BURU1NQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4SERBYUJnTlZCQU1URTJ0MQpZbVZ5Ym1WMFpYTXRVMjkxYkcxaGRHVXdIaGNOTWpBd016SXpNRE13TmpBd1doY05NakV3TXpJek1ETXdOakF3CldqQXVNUXd3Q2dZRFZRUUtFd05yT0hNeER6QU5CZ05WQkFzVEJsTjVjM1JsYlRFTk1Bc0dBMVVFQXhNRWJuVjMKWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3k4Y2c5VUcyYWZYVURJcW9YTQpBQ3p1TmxlcUMvRGhWOGdseUZOU0d3SG94NFFXSDkwMThFQTkvSkc5S0gzL251RUhWZkt6Mm56d2FtSUowSHJ4CnhucmRoeHFmMWF2Z3FZOVZubzVjSU9aLzUrdThNRldQeXZvcUhYeU5BODMxM0RQRTgzSDlOUE9IMkI5emYzSzYKS2xQTHphZndMSVBZdjRBVUdSVmxHMEJwdVBxOUdBRWJmWEY2djRMTTdwL0gweVRScUcweXNtK0NIRkZidzhrOQo2UThZTllRaHFsQ1E3Ym4rbERQcXlLRUZRSWhDbnVuaUgyd0M4dzRnTzArUUZRaVNzMFAyYnZCNGl3S0lxZzRpCjdQdGkrRGZjWHdOS2w5N2FIcmtqbHdGc3V0WWlPWnAvQWRQSjhoRk5ZOWxDc1EyTk84VVlGTnBrVlNsNlVnMVAKZ25VQ0F3RUFBYU9DQVRFd2dnRXRNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRgpCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVcURDQ1oyQVA5dHIxCnhTUGIyd2Q3ZzZnQi9Ic3dId1lEVlIwakJCZ3dGb0FVcklSbTI4b05uZGJ2dGdLbVZhMFZETGp3MVVBd2dhMEcKQTFVZEVRU0JwVENCb29JeGJuVjNZUzFqYjI1MGNtOXNiR1Z5TFcxaGJtRm5aWEl0YzJWeWRtbGpaUzV6ZG1NdQpZMngxYzNSbGNpNXNiMk5oYklJNWJuVjNZUzFqYjI1MGNtOXNiR1Z5TFcxaGJtRm5aWEl0YldWMGNtbGpjeTF6ClpYSjJhV05sTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzZ2l4dWRYZGhMVzUxZDJFdGMybGtaV05oY2kxcGJtcGwKWTNSdmNpNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJY0Vmd0FBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpBbGY1UWc1eEM1eDJHMWJnTzhDb3RBZUN2b3lRTHppdTNlWFpxVVQxQkZ2REYyRUpIZEJHeHUzaVBtVUdEUTJHCnhvNnk3YU5tcjJLWFQxTUxhZURGRnJpZ21JQ0ZyR1RkU0ExNE8rUm5wb28waTZRTUc2L0t0MHlUWlVwUGZDV2IKNDNzc2lCcWFVNWlCdWdIK2E1MnljTUlwa0lNM2pITFlnZytZV3A0cEdqbXNoRisrRWhIWjFQOTRSWXJtVmwxMwpmNlRVYk42eUhwcnJzYUwxdDRienIzZERaZlpPb3daT3RQblVoVUhvWjR4UlJyVzkvem5FWEU2WGZZYjk3YmJWCk83UW1ZMlFQUytLb3QyY1FJSzFpTk12RDdRbFBZNEVhdjdLVTlFZGtNbUZ3cW1PYjZTSlVWOXNMZTJBRnU5eUUKemtqQzczR1Qyb1FtcU5QSzN5M3VGUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name:  controller-manager-service
      namespace: system
      path: /mutating-pods
  failurePolicy: Fail
  name: injector.nuwa.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods