
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nuwa.nip.io
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nuwa.nip.io
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nuwa.nip.io
  resources:
  - sidecars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nuwa.nip.io
  resources:
  - sidecars/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nuwa.nip.io
  resources:
  - stones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nuwa.nip.io
  resources:
  - stones/status
  verbs:
  - get
  - patch
  - update
