# permissions for end users to edit statefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulset-editor-role
rules:
- apiGroups:
  - nuwa.nip.io
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nuwa.nip.io
  resources:
  - statefulsets/status
  verbs:
  - get
