# permissions for end users to view statefulsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulset-viewer-role
rules:
- apiGroups:
  - nuwa.nip.io
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nuwa.nip.io
  resources:
  - statefulsets/status
  verbs:
  - get
