apiVersion: nuwa.nip.io/v1
kind: Sidecar
metadata:
  name: sidecar-sample
spec:
  name: water-sample
  namespace: cert-manager
  resourceType: Water
  containers:
    - name: sidecar1
      image: centos:7
      command: ["sleep", "999d"] # do nothing at all
