apiVersion: nuwa.nip.io/v1
kind: StatefulSet
metadata:
  name: statefulset-sample
spec:
  replicas: 1
  serviceName: fake-service
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
      annotations:
        coordinates: '[{"zone":"A","rack":"W-01","host":"node2","replicas":1},{"zone":"A","rack":"S-02","host":"node3","replicas":1},{"zone":"B","rack":"W-01","host":"node4","replicas":1},{"zone":"B","rack":"S-02","host":"node5","replicas":1}]'
    spec:
      readinessGates:
        - conditionType: InPlaceUpdateReady
      containers:
        - name: main
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: www
              mountPath: "/usr/share/nginx/html"
  volumeClaimTemplates:
    - metadata:
        name: www
        annotations:
          volume.alpha.kubernetes.io/storage-class: default
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      podUpdatePolicy: InPlaceIfPossible
      maxUnavailable: 2
      partition: 1
